### ISSUE TITLE
Minor grammatical error in footer.

### ISSUE THREAD

**Issue by jordanmack** [cryptape/ckb-node-probe-frontend#28]
In the footer, it says "Build by 🦧 with ❤️". To be more grammatically correct, it should be "Built by 🦧 with ❤️".

![20231115223724](https://github.com/cryptape/ckb-node-probe-frontend/assets/37931/3aa14597-a1d2-4558-a5f1-ecae9fc83bb5)

**Comment by lee920217** [comment]
Thank you for your suggestion. The grammar error will be fixed in this [PR](https://github.com/cryptape/ckb-node-probe-frontend/pull/30)
